version: 0.0
# Specify "os: linux" for Amazon Linux, RHEL or Ubuntu Server  
# Specify "os: windows" if this revision targets Windows Server instances.
os: linux 
files:
  - source: /
    destination: /var/www/html/jobportal/
hooks:
# For each deployment lifecycle event, specify multiple "location" entries 
# During the BeforeInstall deployment lifecycle event, run the commands 
#   in the script specified in "location".
  BeforeInstall: 
    - location:  deployment/scripts/BeforeInstall.sh
      timeout: 3000
      runas: root
# During the AfterInstall deployment lifecycle event, run the commands 
#   in the script specified in "location".
  AfterInstall:
    - location: deployment/scripts/AfterInstall.sh
      timeout: 3000
      runas: root
# During the ApplicationStart deployment lifecycle event, run the commands 
#   in the script specified in "location".
#  ApplicationStart:
#    - location:     
#      timeout: 
#      runas:
# During the ValidateService deployment lifecycle event, run the commands 
#   in the script specified in "location".
#  ValidateService:
#    - location:     
#      timeout: 
#      runas:
#    - location: 
#      timeout:
#      runas:
#DeployTest15042024
